apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-04-03T13:55:07Z
  generation: 1
  labels:
    run: kafka-manager
  name: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafka-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kafka-manager
    spec:
      containers:
      - env:
        - name: ZK_HOSTS
          value: {{ .Values.zookeeper_connect }}
        image: ihardz/kafka-manager:latest
        imagePullPolicy: Always
        name: kafka-manager
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager-service
spec:
  selector:
    run: kafka-manager
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
