apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.pvc.storage_class }}"
  labels:
    billingType: "{{ .Values.pvc.billingType }}"
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}      
status:
  accessModes:
  - {{ .Values.pvc.accessModes }}
  capacity:
    storage: {{ .Values.pvc.capacity_storage }}
  phase: {{ .Values.pvc.phase }}
