kind: ConfigMap
apiVersion: v1
metadata:
  name: hive-logging-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: hive
    component: {{ .Values.component }}
data:
  hive-log4j2.properties: |
{{ .Files.Get "hive-log4j2.properties" }}
  log4j.properties: |
{{ .Files.Get "hive-log4j.properties" }}