apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.airflow.serviceAccount.name }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.airflow.clusterRoleBinding.name }}
subjects:
  - kind: {{ .Values.airflow.clusterRoleBinding.kind }}
    name: {{ .Values.airflow.serviceAccount.name }}
roleRef:
  kind: {{ .Values.airflow.clusterRoleBinding.roleRef.kind }}
  name: {{ .Values.airflow.clusterRoleBinding.roleRef.name }}
  apiGroup: {{ .Values.airflow.clusterRoleBinding.roleRef.apiGroup }}