#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
  #name: airflow-ingress
  #annotations:
    #ingress.kubernetes.io/proxy-body-size: "0"
    #ingress.kubernetes.io/proxy-read-timeout: "600"
    #ingress.kubernetes.io/proxy-send-timeout: "600"
    #ingress.bluemix.net/redirect-to-https: "True"
    #ingress.bluemix.net/appid-auth: "bindSecret=binding-epm-sales-app-id namespace=default requestType=web serviceName=airflow"
    #kubernetes.io/ingress.class: "nginx"
    #ingress.bluemix.net/redirect-to-https: "True"
    #nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: basic-auth
    #nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
#spec:
  #tls:
   #- hosts:
     #- {{ .Values.ingress.hosts }}
     #secretName: {{ .Values.ingress.secretName }}
  #rules:
  #- host: {{ .Values.ingress.hosts }}
  #- http:
      #paths:
      #- backend:
          #serviceName: airflow
          #servicePort: 8080
        #path: {{ .Values.ingress.path}}

