apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.airflow.persistentVolumeClaim.name }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.airflow.persistentVolumeClaim.storage }}
  labels:
    billingType: {{ .Values.airflow.persistentVolumeClaim.billingType }}
spec:
  accessModes:
    - {{ .Values.airflow.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.airflow.persistentVolumeClaim.resources }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.airflow.persistentVolumeClaim.name }}-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.airflow.persistentVolumeClaim.storage }}
  labels:
    billingType: {{ .Values.airflow.persistentVolumeClaim.billingType }}
spec:
  accessModes:
    - {{ .Values.airflow.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.airflow.persistentVolumeClaim.resources }}