namespace: elastic
externalIPs: {}
elastic:
  image:
    registry: docker.elastic.co/elasticsearch/elasticsearch-oss
    tag: 6.3.1
    imagePullPolicy: Always
  securityContext:
    privileged: true
    runAsUser: 0
  ports:
    clientport: 9200
    transportport: 9300
  livenessProbe:
    failureThreshold: 6
    initialDelaySeconds: 120
    periodSeconds: 50
    successThreshold: 1
    timeoutSeconds: 3
  volumes:
    configMap:
      defaultMode: 420
    hostPath:
      type: DirectoryOrCreate

  master:
    app: es-master
    name: es-master
    replicas: 2
    revisionHistoryLimit: 10
    jvmHeapSize: 512m
  data:
    app: es-data
    name: es-data
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    jvmHeapSize: 2g
    volumeClaimTemplates:
      spec:
        resources:
          storage: 2Gi
          iops: "6000"

kibana:
  component: kibana
  replicas: 1
  image:
    registry: docker.elastic.co/kibana/kibana-oss
    tag: 6.3.1
  resources:
    limits:
      memory: "3Gi"
      cpu: "3"
    requests:
      memory: "500Mi"
      cpu: "0.1"
  ports:
    containerPort: 5601
