namespace: airflow

#ingress:
  #hosts: airflow.mpw-development.us-south.containers.appdomain.cloud
  #secretName: airflow
  #path: /mpw-staging/airflow
  
airflow:
  name: airflow
  image:
    repository: gmlclusterm01.gomel.iba.by/test/airflow-custom
    tag: v1.0
    pullPolicy: Always
    #pullSecrets: ""
  replicas: 1
  containerPort: 8080
  livenessProbe:
    initialDelaySeconds: 600
    timeoutSeconds: 5
    failureThreshold: 5
    path: /login
    port: 8080
  service:
    name: airflow
    port: 8080
    targetPort: 8080
    type: ClusterIP
    externalIPs: 169.61.14.164
  serviceAccount:
    name: airflow-sa
  clusterRoleBinding:
    name: airflow-sa-rb
    kind: ServiceAccount
    roleRef:
      kind: ClusterRole
      name: edit
      apiGroup: rbac.authorization.k8s.io
  persistentVolumeClaim:
    name: pvc
    storage: "gomel-nfs"
    billingType: "hourly"
    accessModes: ReadWriteMany
    resources: 1Gi

postgres:
  name: postgres
  label: postgres
  restartPolicy: Always
  #pullSecrets: ""
  containers:
    name: postgres
  image: 
    registry: postgres
    tag: 11
    imagePullPolicy: Always
  ports:
    containerPort: 5432
    protocol: TCP
  livenessProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 5
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 5
    periodSeconds: 5
  resources:
    requests:
      memory: .5Gi
      cpu: .5
  volumes:
    name: vol
    persistentVolumeClaim:
      claimName: pvc
  service:
    name: postgres
    ports:
      port: 5432
      targetPort: 5432

secrets:
  name: airflow-secrets
  type: Opaque
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3Jvb3Q6cm9vdEBwb3N0Z3Jlczo1NDMyL2FpcmZsb3cK
