apiVersion: v1
kind: ConfigMap
metadata:
  name: conductor-cm
data:
  conductor-server.properties: |
    db={{ $.Values.db }}
    jdbc.url={{ $.Values.jdbcUrl }}
    jdbc.username={{ $.Values.jdbcUserName }}
    jdbc.password={{ $.Values.jdbcPassword }}
    # Transport address to elasticsearch
    workflow.elasticsearch.url={{ $.Values.esUrl }}
    workflow.elasticsearch.cluster.name={{ $.Values.esClusterName }}
    workflow.elasticsearch.index.name=conductor
    # Load sample kitchen sink workflow
    loadSample=false
  log4j.properties: |
    log4j.rootLogger=INFO,stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%p\t%d{ISO8601}\t%r\t%c\t[%t]\t%m%n
---
apiVersion: v1
kind: Service
metadata:
  name: conductor-svc
  labels:
    app: conductor
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "conductor"
spec:
  clusterIP: None 
  ports:
  - name: ui
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: conductor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: conductor
  labels:
    app: conductor
spec:
  serviceName: conductor-svc
  replicas: {{ .Values.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: conductor
  template:
    metadata:
      labels:
        app: conductor
    spec:
      containers:
      - name: conductor-server
        image: ihardz/conductor-server:latest
        env:
        - name: CONDUCTOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /bin/sh
        - -c
        - java -jar /app/libs/conductor-server-*-all.jar /app/config/conductor-server.properties /app/config/log4j.properties
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        volumeMounts:
        - name: conductor-config
          mountPath: /app/config/conductor-server.properties
          subPath: conductor-server.properties
        - name: conductor-config
          mountPath: /app/config/log4j.properties
          subPath: log4j.properties
      - name: conductor-ui
        image: ihardz/conductor-ui:latest
        ports:
        - containerPort: 5000
          name: server
          protocol: TCP
      volumes:
      - name: conductor-config
        configMap:
          name: conductor-cm