apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-data-svc
  name: es-data-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: client
    port: {{ .Values.elastic.ports.clientport }}
    protocol: TCP
    targetPort: {{ .Values.elastic.ports.clientport }}
  - name: transport
    port: {{ .Values.elastic.ports.transportport }}
    protocol: TCP
    targetPort: {{ .Values.elastic.ports.transportport }}
  selector:
    app: {{ .Values.elastic.data.app }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-master-svc
  name: es-master-svc
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  ports:
  - name: client
    port: {{ .Values.elastic.ports.clientport }}
    protocol: TCP
    targetPort: {{ .Values.elastic.ports.clientport }}
  - name: transport
    port: {{ .Values.elastic.ports.transportport }}
    protocol: TCP
    targetPort: {{ .Values.elastic.ports.transportport }}
  selector:
    app: {{ .Values.elastic.master.app }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-ext-svc
  name: es-ext-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: client
    port: {{ .Values.elastic.ports.clientport }}
    protocol: TCP
    targetPort: {{ .Values.elastic.ports.clientport }}
  selector:
    app: {{ .Values.elastic.master.app }}
  type: ClusterIP
  externalIPs:
  - {{ .Values.externalIPs }}